language: python
sudo: false
python:
- '3.5'

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.cache/pip


install: 
  - pip install pip==9.0.1
  - pip install -r requirements/dev.txt
  - pip install coveralls

env:
  - DJANGO_SETTINGS_MODULE="settings.testing"

script:
- flake8
- py.test --splinter-webdriver=phantomjs --cov -v --tb=native
- coverage report -m

after_success:
  coveralls


notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]

services:
  - redis-server
