language: python
sudo: false

python:
- '3.5'

addons:
  postgresql: "9.4"
  firefox: "60.0.2"

services:
  - xvfb

cache:
  pip: true

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_script:
- psql -c "CREATE DATABASE wye" -U postgres

before_install:
  - "export DISPLAY=:99.0"
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
- pip install -r requirements/dev.txt
- pip install python-coveralls

script:
- flake8
- py.test --cov --fail-on-template-vars --splinter-webdriver=firefox -v --tb=native

after_script:
- coveralls

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
